name = "ThreadedIterables"
uuid = "11d239b0-c0b9-11e8-1935-d5cfa53abb03"
authors = ["Marek Dědič <developer@dedic.eu>"]
version = "0.2.0"

[compat]
julia = "^1.0.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
